/*
 * This file is generated by the configuration script sys/conf/config.
 *
 * It contains a list of kernel options, used when compiling the kernel
 * as well as in a few of the application programs.
 *
 * All defines previously found in the whoami.h file have been moved
 * into this file, as well as several originally found in device header
 * files.  Do not hand edit unless you know what you're doing.  (You
 * probably shouldn't hand edit anyway...)  See sys/conf/GENERIC for a
 * list of available options and explanation as to what an option does,
 * and sys/conf/README for more information.
 */

#define PDP11	GENERIC
#define MAXMEM	(200*16)
#define LINEHZ	60
#ifdef KERNEL
#define NBUF	60
#define UNIBUS_MAP 1
#define VIRUS_VFORK 1
#define UCB_RUSAGE 1
#endif /* KERNEL */
